// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

/**
 * Verse represents a single Bible verse
 */
export interface Verse {
  book_id: string;
  book_name: string;
  chapter: number /* int */;
  verse: number /* int */;
  text: string;
}
/**
 * BibleResponse represents the API response for Bible passages
 */
export interface BibleResponse {
  reference: string;
  verses: Verse[];
  text: string;
  translation_id: string;
  translation_name: string;
  translation_note: string;
}
/**
 * Translation represents a Bible translation
 */
export interface Translation {
  id: string;
  name: string;
  note: string;
}
/**
 * Book represents a Bible book
 */
export interface Book {
  id: string;
  name: string;
  chapters: number /* int */;
}
